onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb/clk
add wave -noupdate /tb/reset
add wave -noupdate /tb/new_risc/PC_Out
add wave -noupdate /tb/new_risc/Instruction
add wave -noupdate /tb/new_risc/im/Inst_Address
add wave -noupdate /tb/new_risc/rs1
add wave -noupdate /tb/new_risc/rs2
add wave -noupdate /tb/new_risc/rd
add wave -noupdate /tb/new_risc/imm_data
add wave -noupdate /tb/new_risc/ReadData1
add wave -noupdate /tb/new_risc/ReadData2
add wave -noupdate /tb/new_risc/big1/WriteData
add wave -noupdate /tb/new_risc/big2/WriteData
add wave -noupdate /tb/new_risc/ALU/a
add wave -noupdate /tb/new_risc/ALU/b
add wave -noupdate /tb/new_risc/ALU/Result
add wave -noupdate /tb/new_risc/ALU/ZERO
add wave -noupdate /tb/new_risc/ALU/GEQ
add wave -noupdate -divider Memory
add wave -noupdate /tb/new_risc/big1/Mem_Addr
add wave -noupdate /tb/new_risc/big2/Mem_Addr
add wave -noupdate -expand /tb/new_risc/dm/DataMemory
add wave -noupdate -divider Registers
add wave -noupdate -expand /tb/new_risc/registers/Registers
add wave -noupdate -divider Others
add wave -noupdate /tb/new_risc/reset
add wave -noupdate /tb/new_risc/PC_In
add wave -noupdate /tb/new_risc/PC_Out_ifid
add wave -noupdate /tb/new_risc/Instruction_ifid
add wave -noupdate /tb/new_risc/clk
add wave -noupdate /tb/new_risc/opcode
add wave -noupdate /tb/new_risc/funct3
add wave -noupdate /tb/new_risc/funct7
add wave -noupdate /tb/new_risc/Branch
add wave -noupdate /tb/new_risc/MemRead
add wave -noupdate /tb/new_risc/MemtoReg
add wave -noupdate /tb/new_risc/ALUOp
add wave -noupdate /tb/new_risc/MemWrite
add wave -noupdate /tb/new_risc/ALUSrc
add wave -noupdate /tb/new_risc/RegWrite
add wave -noupdate /tb/new_risc/instruction_idex
add wave -noupdate /tb/new_risc/rs1_idex
add wave -noupdate /tb/new_risc/rs2_idex
add wave -noupdate /tb/new_risc/rd_idex
add wave -noupdate /tb/new_risc/imm_data_idex
add wave -noupdate /tb/new_risc/ReadData1_idex
add wave -noupdate /tb/new_risc/ReadData2_idex
add wave -noupdate /tb/new_risc/PC_Out_idex
add wave -noupdate /tb/new_risc/ALUSrc_idex
add wave -noupdate /tb/new_risc/ALUOp_idex
add wave -noupdate /tb/new_risc/Branch_idex
add wave -noupdate /tb/new_risc/MemRead_idex
add wave -noupdate /tb/new_risc/MemWrite_idex
add wave -noupdate /tb/new_risc/RegWrite_idex
add wave -noupdate /tb/new_risc/MemtoReg_idex
add wave -noupdate /tb/new_risc/adder2_output
add wave -noupdate /tb/new_risc/BigMux1_output
add wave -noupdate /tb/new_risc/BigMux2_output
add wave -noupdate /tb/new_risc/alusrc_mux_output
add wave -noupdate /tb/new_risc/ZERO
add wave -noupdate /tb/new_risc/ALU_64_bit_Result
add wave -noupdate /tb/new_risc/rd_exmem
add wave -noupdate /tb/new_risc/mux_out_exmem
add wave -noupdate /tb/new_risc/ALU_res_exmem
add wave -noupdate /tb/new_risc/Adder_exmem
add wave -noupdate /tb/new_risc/funct3_exmem
add wave -noupdate /tb/new_risc/GEQ_exmem
add wave -noupdate /tb/new_risc/ZERO_exmem
add wave -noupdate /tb/new_risc/Branch_exmem
add wave -noupdate /tb/new_risc/MemRead_exmem
add wave -noupdate /tb/new_risc/MemWrite_exmem
add wave -noupdate /tb/new_risc/MemtoReg_exmem
add wave -noupdate /tb/new_risc/Operation
add wave -noupdate /tb/new_risc/Read_Data_DataMemory
add wave -noupdate /tb/new_risc/green
add wave -noupdate /tb/new_risc/Read_Data_memwb
add wave -noupdate /tb/new_risc/ALU_Res_memwb
add wave -noupdate /tb/new_risc/RegWrite_memwb
add wave -noupdate /tb/new_risc/MemtoReg_memwb
add wave -noupdate /tb/new_risc/brown
add wave -noupdate /tb/new_risc/Forward_A
add wave -noupdate /tb/new_risc/Forward_B
add wave -noupdate /tb/new_risc/Branch_mux_output
add wave -noupdate /tb/new_risc/Adder_1_output
add wave -noupdate /tb/new_risc/GEQ
add wave -noupdate /tb/new_risc/RegWrite_exmem
add wave -noupdate /tb/new_risc/pc/PC_In
add wave -noupdate /tb/new_risc/pc/clk
add wave -noupdate /tb/new_risc/pc/reset
add wave -noupdate /tb/new_risc/pc/PC_Out
add wave -noupdate /tb/new_risc/im/Instruction
add wave -noupdate /tb/new_risc/adder1/a
add wave -noupdate /tb/new_risc/adder1/b
add wave -noupdate /tb/new_risc/adder1/out
add wave -noupdate /tb/new_risc/IfId/PC_Out
add wave -noupdate /tb/new_risc/IfId/Instruction
add wave -noupdate /tb/new_risc/IfId/clk
add wave -noupdate /tb/new_risc/IfId/reset
add wave -noupdate /tb/new_risc/IfId/PC_Out_out
add wave -noupdate /tb/new_risc/IfId/Instruction_out
add wave -noupdate /tb/new_risc/ip/instruction
add wave -noupdate /tb/new_risc/ip/opcode
add wave -noupdate /tb/new_risc/ip/rd
add wave -noupdate /tb/new_risc/ip/funct3
add wave -noupdate /tb/new_risc/ip/rs1
add wave -noupdate /tb/new_risc/ip/rs2
add wave -noupdate /tb/new_risc/ip/funct7
add wave -noupdate /tb/new_risc/registers/WriteData
add wave -noupdate /tb/new_risc/registers/RS1
add wave -noupdate /tb/new_risc/registers/RS2
add wave -noupdate /tb/new_risc/registers/RD
add wave -noupdate /tb/new_risc/registers/RegWrite
add wave -noupdate /tb/new_risc/registers/clk
add wave -noupdate /tb/new_risc/registers/reset
add wave -noupdate /tb/new_risc/registers/ReadData1
add wave -noupdate /tb/new_risc/registers/ReadData2
add wave -noupdate /tb/new_risc/cu/Opcode
add wave -noupdate /tb/new_risc/cu/Branch
add wave -noupdate /tb/new_risc/cu/MemRead
add wave -noupdate /tb/new_risc/cu/MemtoReg
add wave -noupdate /tb/new_risc/cu/ALUOp
add wave -noupdate /tb/new_risc/cu/MemWrite
add wave -noupdate /tb/new_risc/cu/ALUSrc
add wave -noupdate /tb/new_risc/cu/RegWrite
add wave -noupdate /tb/new_risc/ime/instruction
add wave -noupdate /tb/new_risc/ime/imm_data
add wave -noupdate /tb/new_risc/ime/opcode
add wave -noupdate /tb/new_risc/idex/instruction
add wave -noupdate /tb/new_risc/idex/rs1
add wave -noupdate /tb/new_risc/idex/rs2
add wave -noupdate /tb/new_risc/idex/rd
add wave -noupdate /tb/new_risc/idex/imm_data
add wave -noupdate /tb/new_risc/idex/ReadData1
add wave -noupdate /tb/new_risc/idex/ReadData2
add wave -noupdate /tb/new_risc/idex/PC_Out
add wave -noupdate /tb/new_risc/idex/ALUSrc
add wave -noupdate /tb/new_risc/idex/ALUOp
add wave -noupdate /tb/new_risc/idex/Branch
add wave -noupdate /tb/new_risc/idex/MemRead
add wave -noupdate /tb/new_risc/idex/MemWrite
add wave -noupdate /tb/new_risc/idex/RegWrite
add wave -noupdate /tb/new_risc/idex/MemtoReg
add wave -noupdate /tb/new_risc/idex/clk
add wave -noupdate /tb/new_risc/idex/reset
add wave -noupdate /tb/new_risc/idex/instruction_out
add wave -noupdate /tb/new_risc/idex/rs1_out
add wave -noupdate /tb/new_risc/idex/rs2_out
add wave -noupdate /tb/new_risc/idex/rd_out
add wave -noupdate /tb/new_risc/idex/imm_data_out
add wave -noupdate /tb/new_risc/idex/ReadData1_out
add wave -noupdate /tb/new_risc/idex/ReadData2_out
add wave -noupdate /tb/new_risc/idex/PC_Out_out
add wave -noupdate /tb/new_risc/idex/ALUSrc_out
add wave -noupdate /tb/new_risc/idex/ALUOp_out
add wave -noupdate /tb/new_risc/idex/Branch_out
add wave -noupdate /tb/new_risc/idex/MemRead_out
add wave -noupdate /tb/new_risc/idex/MemWrite_out
add wave -noupdate /tb/new_risc/idex/RegWrite_out
add wave -noupdate /tb/new_risc/idex/MemtoReg_out
add wave -noupdate /tb/new_risc/adder2/a
add wave -noupdate /tb/new_risc/adder2/b
add wave -noupdate /tb/new_risc/adder2/out
add wave -noupdate /tb/new_risc/big1/ReadData
add wave -noupdate /tb/new_risc/big1/sel
add wave -noupdate /tb/new_risc/big1/BigMuxOutput
add wave -noupdate /tb/new_risc/big2/ReadData
add wave -noupdate /tb/new_risc/big2/sel
add wave -noupdate /tb/new_risc/big2/BigMuxOutput
add wave -noupdate /tb/new_risc/ALUSrc_MUX/a
add wave -noupdate /tb/new_risc/ALUSrc_MUX/b
add wave -noupdate /tb/new_risc/ALUSrc_MUX/sel
add wave -noupdate /tb/new_risc/ALUSrc_MUX/data_out
add wave -noupdate /tb/new_risc/alu_control/ALUOp
add wave -noupdate /tb/new_risc/alu_control/Funct
add wave -noupdate /tb/new_risc/alu_control/Operation
add wave -noupdate /tb/new_risc/ALU/ALUOp
add wave -noupdate /tb/new_risc/exmem/Rd
add wave -noupdate /tb/new_risc/exmem/Mux
add wave -noupdate /tb/new_risc/exmem/ALU_Res
add wave -noupdate /tb/new_risc/exmem/Adder_out
add wave -noupdate /tb/new_risc/exmem/funct3
add wave -noupdate /tb/new_risc/exmem/GEQ
add wave -noupdate /tb/new_risc/exmem/Zero
add wave -noupdate /tb/new_risc/exmem/Branch
add wave -noupdate /tb/new_risc/exmem/MemRead
add wave -noupdate /tb/new_risc/exmem/MemWrite
add wave -noupdate /tb/new_risc/exmem/RegWrite
add wave -noupdate /tb/new_risc/exmem/MemtoReg
add wave -noupdate /tb/new_risc/exmem/clk
add wave -noupdate /tb/new_risc/exmem/reset
add wave -noupdate /tb/new_risc/exmem/Rd_out
add wave -noupdate /tb/new_risc/exmem/Mux_out
add wave -noupdate /tb/new_risc/exmem/ALU_Res_out
add wave -noupdate /tb/new_risc/exmem/Adder_out_out
add wave -noupdate /tb/new_risc/exmem/funct3_out
add wave -noupdate /tb/new_risc/exmem/GEQ_out
add wave -noupdate /tb/new_risc/exmem/Zero_out
add wave -noupdate /tb/new_risc/exmem/Branch_out
add wave -noupdate /tb/new_risc/exmem/MemRead_out
add wave -noupdate /tb/new_risc/exmem/MemWrite_out
add wave -noupdate /tb/new_risc/exmem/RegWrite_out
add wave -noupdate /tb/new_risc/exmem/MemtoReg_out
add wave -noupdate /tb/new_risc/dm/Mem_Addr
add wave -noupdate /tb/new_risc/dm/Write_Data
add wave -noupdate /tb/new_risc/dm/clk
add wave -noupdate /tb/new_risc/dm/MemWrite
add wave -noupdate /tb/new_risc/dm/MemRead
add wave -noupdate /tb/new_risc/dm/Read_Data
add wave -noupdate /tb/new_risc/memwb/Rd
add wave -noupdate /tb/new_risc/memwb/Read_Data
add wave -noupdate /tb/new_risc/memwb/ALU_Res
add wave -noupdate /tb/new_risc/memwb/RegWrite
add wave -noupdate /tb/new_risc/memwb/MemtoReg
add wave -noupdate /tb/new_risc/memwb/clk
add wave -noupdate /tb/new_risc/memwb/reset
add wave -noupdate /tb/new_risc/memwb/Rd_out
add wave -noupdate /tb/new_risc/memwb/Read_Data_out
add wave -noupdate /tb/new_risc/memwb/ALU_Res_out
add wave -noupdate /tb/new_risc/memwb/RegWrite_out
add wave -noupdate /tb/new_risc/memwb/MemtoReg_out
add wave -noupdate /tb/new_risc/MemtoReg_MUX/a
add wave -noupdate /tb/new_risc/MemtoReg_MUX/b
add wave -noupdate /tb/new_risc/MemtoReg_MUX/sel
add wave -noupdate /tb/new_risc/MemtoReg_MUX/data_out
add wave -noupdate /tb/new_risc/fd/Rs1
add wave -noupdate /tb/new_risc/fd/Rs2
add wave -noupdate /tb/new_risc/fd/Rd_EX_MEM
add wave -noupdate /tb/new_risc/fd/Rd_MEM_WB
add wave -noupdate /tb/new_risc/fd/RegWrite_EX_MEM
add wave -noupdate /tb/new_risc/fd/RegWrite_MEM_WB
add wave -noupdate /tb/new_risc/fd/Forward_A
add wave -noupdate /tb/new_risc/fd/Forward_B
add wave -noupdate /tb/new_risc/Branch_MUX/a
add wave -noupdate /tb/new_risc/Branch_MUX/b
add wave -noupdate /tb/new_risc/Branch_MUX/sel
add wave -noupdate /tb/new_risc/Branch_MUX/data_out
add wave -noupdate /tb/clk
add wave -noupdate /tb/reset
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {45 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 403
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {27 ns} {81 ns}
